"""changes

Revision ID: 200971c2f15f
Revises: 9e2fe0290a98
Create Date: 2024-03-12 22:05:17.161483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '200971c2f15f'
down_revision = '9e2fe0290a98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
